#!/usr/bin/env python

Import('env')

Lib_Name = 'gpioLib'

Source_Files = [
	'gpio.c'
	]
	

program = env.createLibrary(libraryName=Lib_Name, outputDirectory = '../lib', sourceFiles = Source_Files)

Lib_Name = 'uartLib'

Source_Files = [
	'uart.c'
	]

program = env.createLibrary(libraryName=Lib_Name, outputDirectory = '../lib', sourceFiles = Source_Files)


